### קבלת כל הפוסטים
GET http://localhost:8080/posts
Content-Type: application/json

###

### יצירת פוסט חדש
POST http://localhost:8080/posts
Content-Type: application/json

{
    "sender": "Naomi",
    "type": "lost",
    "animalType": "dog",
    "location": {
        "type": "Point",
        "coordinates": [34.7818, 32.0853],
        "address": "Tel Aviv"
    },
    "dateTimeOccured": "2026-01-10T20:00:00Z",
    "description": "Golden Retriever lost near the park"
}