###
GET http://localhost:8080/posts

###
POST http://localhost:8080/posts
Content-Type: application/json

{
  "sender": "Yuval",
  "type": "found",
  "animalType": "dog",
  "location": {
    "type": "Point",
    "coordinates": [12.345, 67.890]
  },
  "dateTimeOccured": "2026-01-30T14:00:00Z",
  "description": "White dog with a black collar",
  "isResolved": true
}

###
GET  http://localhost:8080/posts/697cac6c7e62586c69ef4965

###
GET  http://localhost:8080/posts?sender=Yuval

###
PUT http://localhost:8080/posts/697cac6c7e62586c69ef4965
Content-Type: application/json

{
  "sender": "Yuval",
  "type": "found",
  "animalType": "bird",
  "location": {
    "type": "Point",
    "coordinates": [67.890, 12.345]
  },
  "dateTimeOccured": "2026-01-30T14:00:00Z",
  "description": "White bird",
  "isResolved": false
}

###
GET http://localhost:8080/comments

###
GET http://localhost:8080/comments/697cce6664aa66305322b225

###
POST  http://localhost:8080/comments
Content-Type: application/json

{
  "postId": "697cac6c7e62586c69ef4965",
  "sender": "Naomi",
  "commentText": "I think I saw this bird near the park."
}

###
GET http://localhost:8080/comments/post/697cac6c7e62586c69ef4965

###
PATCH http://localhost:8080/comments/697cce6664aa66305322b225
Content-Type: application/json

{
  "commentText": "Actually, looking closer, I think it is a different species."
}

###
DELETE http://localhost:8080/comments/697cce6664aa66305322b225