###
GET http://localhost:8080/posts

###
POST http://localhost:8080/posts
Content-Type: application/json

{
  "sender": "Naomi",
  "type": "lost",
  "animalType": "hamster",
  "location": {
    "type": "Point",
    "coordinates": [12.345, 67.890]
  },
  "dateTimeOccured": "2026-01-16T14:00:00Z",
  "description": "Hamster with a red bow tie.",
  "isResolved": false,
  "photos": [
    "https://placedog.net/600"
  ]
}

###
GET http://localhost:8080/posts/697cda4d909448ce1d1d6681

###
GET http://localhost:8080/posts?sender=Naomi

###
PUT http://localhost:8080/posts/6962b723b6737e046a1aaa33
Content-Type: application/json

{
  "sender": "Yuval",
  "type": "found",
  "animalType": "bird",
  "location": {
    "type": "Point",
    "coordinates": [67.890, 12.345]
  },
  "dateTimeOccured": "2026-01-30T14:00:00Z",
  "description": "Editing: Actually it was a white bird, not a dog.",
  "isResolved": false,
  "photos": [
    "https://placedog.net/500"
  ]
}

###
GET http://localhost:8080/comments

###
GET http://localhost:8080/comments?postId=697cac6c7e62586c69ef4965

###
GET http://localhost:8080/comments/697cce6664aa66305322b225

###
POST  http://localhost:8080/comments
Content-Type: application/json

{
  "postId": "697cac6c7e62586c69ef4965",
  "sender": "Naomi",
  "commentText": "I think I saw this bird near the park."
}

###
PUT http://localhost:8080/comments/697cdf229c5395dfa9477955
Content-Type: application/json

{
  "commentText": "Editing: Actually, looking closer, I think it is a different species."
}

###
DELETE http://localhost:8080/comments/697cce6664aa66305322b225