###
GET http://localhost:8080/post

###
POST http://localhost:8080/post
Content-Type: application/json

{
  "sender": "Yuval",
  "type": "lost",
  "animalType": "horse",
  "location": {
    "type": "Point",
    "coordinates": [12.345, 67.890]
  },
  "dateTimeOccured": "2026-01-17T14:00:00Z",
  "description": "Horse with a red bow tie.",
  "isResolved": false,
  "photos": [
    "https://placedog.net/600"
  ]
}

###
GET http://localhost:8080/post/697cea427a339ea2dda762d5

###
GET http://localhost:8080/post?sender=Yuval

###
PUT http://localhost:8080/post/697cea427a339ea2dda762d5
Content-Type: application/json

{
  "sender": "Yuval",
  "type": "found",
  "animalType": "horse",
  "location": {
    "type": "Point",
    "coordinates": [67.890, 12.345]
  },
  "dateTimeOccured": "2026-01-12T14:00:00Z",
  "description": "Editing: Actually the bow was pink.",
  "isResolved": false,
  "photos": [
    "https://placedog.net/500"
  ]
}

###
GET http://localhost:8080/comment

###
GET http://localhost:8080/comment?postId=697cac6c7e62586c69ef4965

###
GET http://localhost:8080/comment/697cdf229c5395dfa9477955

###
POST  http://localhost:8080/comment
Content-Type: application/json

{
  "postId": "697cac6c7e62586c69ef4965",
  "sender": "Yuval",
  "commentText": "I saw the horse on the road."
}

###
PUT http://localhost:8080/comment/697ceac87a339ea2dda762e3
Content-Type: application/json

{
  "commentText": "Editing: I saw the horse on the road: The road is Derech Ben Gurion."
}

###
DELETE http://localhost:8080/comment/697ceac87a339ea2dda762e3